//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarcet.Qoute.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QouteDetails
    {
        public string Id { get; set; }
        public string QouteId { get; set; }
        public string ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Qoutes Qoutes { get; set; }
        public virtual Products Products { get; set; }
    }
}
